### ISSUE TITLE
Add email-friendly image attribute to apps feed

### ISSUE THREAD

**Issue by markmhendrickson** [blockstackpbc/app.co-api#2]
To ensure that all images are provided as PNG through that attribute since @cuevasm is using a mailer that doesn't support SVG.

Please notify @cuevasm once this attribute is live so he can switch his mailer to using it.

**Comment by hstove** [comment]
@cuevasm this was fixed in the commit a986ab9. We actually fixed SVG format, so most email clients would work now, but some still don't support SVG.

I changed the RSS feed to always include the PNG format of the image. There are no changes required on your end.
